# Generated by Django 4.1.3 on 2022-11-30 13:14

from django.db import migrations, models
import django.db.models.deletion
import rest_api.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, default='subscriber', max_length=255, validators=[rest_api.validators.tag_exists])),
                ('phone_number', models.CharField(max_length=11, validators=[rest_api.validators.is_digit, rest_api.validators.is_a_phone_number])),
                ('mobile_operator_code', models.CharField(max_length=255, validators=[rest_api.validators.is_digit])),
                ('timezone', models.CharField(blank=True, default='Europe/London', max_length=255, validators=[rest_api.validators.timezone_exists])),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('datetime_start', models.DateTimeField(verbose_name='Date and time of mailing start')),
                ('datetime_end', models.DateTimeField(verbose_name='Date and time of mailing end')),
                ('client_tag', models.CharField(max_length=255, validators=[rest_api.validators.tag_exists])),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.mailing')),
            ],
        ),
    ]
